command:
  - streamlit
  - run
  - app.py
  - --server.port
  - "8000"
  - --server.enableCORS
  - "false"
  - --server.enableXsrfProtection
  - "true"
env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: ONR_CATALOG
    value: workspace
  - name: ONR_SCHEMA
    value: default
  - name: ONR_WORKSPACE_HOST
    value: https://dbc-ae83c2ba-d87c.cloud.databricks.com
